name: Trigger auto deployment for plan-nexus-alunos

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/plan-nexus-alunos-AutoDeployTrigger-1b54dd1d-e1af-4425-9866-f67225297f8f.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.PLANNEXUSALUNOS_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.PLANNEXUSALUNOS_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.PLANNEXUSALUNOS_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }} 
          registryUrl: acrplannexus.azurecr.io
          registryUsername: ${{ secrets.PLANNEXUSALUNOS_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.PLANNEXUSALUNOS_REGISTRY_PASSWORD }}
          containerAppName: plan-nexus-alunos
          resourceGroup: plan-nexus
          imageToBuild: acrplannexus.azurecr.io/plan-nexus-alunos:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


